<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GameRouteOptimizer.Service</RootNamespace>
    <AssemblyName>GameRouteOptimizer.Service</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameRouteOptimizer.Core\GameRouteOptimizer.Core.csproj" />
  </ItemGroup>

</Project>
